### ISSUE TITLE
nan when training two stream model (a different one)

### ISSUE THREAD

**Issue by richardkxu** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#18]
Hi,

Thank you for making the code and pre-trained model available. I have encountered "nan" stream1 avg loss when training the two stream model. I have tried the solution you mentioned in **issue #13**, and it worked for the first 3 epochs. However, starting epoch-3, stream1 avg loss turned "nan" while stream2 avg loss looked normal. As a result, I got an error complaning about "nan" when computing the accuracy.

Here are my parameters in main.py:
```
DATA = 'APOL'
SUFIX = '1st'
s2 = True
TRAIN = True
EVAL = True
epochs = 15
train_seq_len = 20
pred_seq_len = 30
```

And here are the logs and error messages:
```
# 0/15 epoch 38/39 batch
stream1 average loss: 160.8448742597531
stream2 average loss: 0.5018476685449386

# 1/15 epoch 38/39 batch
stream1 average loss: 116.52165906857222
stream2 average loss: 0.013798081793655187

# 2/15 epoch 38/39 batch
stream1 average loss: 94.4479136344714
stream2 average loss: 0.007915522234562116

# 3/15 epoch 38/39 batch
stream1 average loss: nan
stream2 average loss: 0.005519000885005181

...
then it always gives "nan" for stream1
...

# 14/15 epoch 38/39 batch
stream1 average loss: nan
stream2 average loss: 0.17809374287772256
computing accuracy...
0/15 in computing accuracy...
Traceback (most recent call last):
  File "/home/richardkxu/Documents/Spectral-Trajectory-and-Behavior-Prediction/ours/main.py", line 69, in <module>
    encoder1, decoder1 = trainIters(epochs, tr_seq_1 , pred_seq_1, tr_seq_2, pred_seq_2, tr_eig_seq, pred_eig_seq, DATA, SUFIX, s2, print_every=1, save_every=save_per_epochs)
  File "/home/richardkxu/Documents/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 179, in trainIters
    if epoch % save_every == 0:
  File "/home/richardkxu/Documents/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 446, in compute_accuracy_stream1
    testbatch_in_form = torch.Tensor ( testbatch_in_form )
  File "/home/richardkxu/Documents/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 290, in generate
    mu1_current = mu_1[ i , : , : ]
  File "/home/richardkxu/Documents/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 379, in sample
    mu = np.array([mu_1[i][0].item(), mu_2[i][0].item()])
  File "mtrand.pyx", line 4535, in mtrand.RandomState.multivariate_normal
  File "/home/richardkxu/anaconda3/envs/sc-glstm/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home/richardkxu/anaconda3/envs/sc-glstm/lib/python3.7/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "/home/richardkxu/anaconda3/envs/sc-glstm/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

Process finished with exit code 1
```

Thank you very much!

**Comment by rayguan97** [comment]
I noticed that you used prediction length of 20-30. You should use 6 as input and 10 as output for APOL. Sorry for not clearing this up. Let me know if the issue persist.

**Comment by richardkxu** [comment]
Thank you for the rely! I am able to resolve the "nan" problem for APOL and get the following results:
```
start evaluating APOL1st...
computing accuracy...
0/10 in computing accuracy...
2/10 in computing accuracy...
4/10 in computing accuracy...
6/10 in computing accuracy...
8/10 in computing accuracy...
ADE: [0.02698119 0.02707643 0.02711591 0.02724386 0.02724257 0.02724447
 0.02704212 0.02690786 0.02670506 0.02652248]
ADE: 0.027008196339011192 FDE: 0.026522482559084893
```

Another question is: it seems like currently we only have eval code for stream1 model. Is this the case?

**Comment by rohanchandra30** [comment]
You can also evaluate stream 1 and stream 2 both. But currently we do not have eval code for stream 2 only.

**Comment by richardkxu** [comment]
Cool, thanks!
