### ISSUE TITLE
Error when running python setup.py

### ISSUE THREAD

**Issue by lylyjy** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#45]
Can you tell me how to solve this error?Thanks

Downloading file from google drive...
Traceback (most recent call last):
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f3700ee50>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1RKcJf6oD3qoVBmZLtIXuLFdAtRKcJDCc (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f3700ee50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    download_file_from_google_drive(file_id, destination)
  File "setup.py", line 13, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lyl/miniconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1RKcJf6oD3qoVBmZLtIXuLFdAtRKcJDCc (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f3700ee50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by Xiejc97** [comment]
I also meet the similar question when I run the setup.py, so how do you deal with this problem? 

Can you tell me, thank you very much!

**Comment by rohanchandra30** [comment]
Check your network. It seems like a network issue. Use VPNs if necessary.
